  test_dodawanie:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run test
        run: pytest Lab_7/env_416404/calculator_test.py::test_dodawanie

  test_odejmowanie:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run test
        run: pytest Lab_7/env_416404/calculator_test.py::test_odejmowanie

  test_mnozenie:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run test
        run: pytest Lab_7/env_416404/calculator_test.py::test_mnozenie

  test_dzielenie:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run test
        run: pytest Lab_7/env_416404/calculator_test.py::test_dzielenie

  test_maksimum:
    runs-on: ubuntu-latest
    needs: [build, test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    steps:
      - name: Run test
        run: pytest Lab_7/env_416404/calculator_test.py::test_maksimum

  test_minimum:
    runs-on: ubuntu-latest
    needs: [build, test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    steps:
      - name: Run test
        run: pytest Lab_7/env_416404/calculator_test.py::test_minimum

  test_srednia:
    runs-on: ubuntu-latest
    needs: [build, test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    steps:
      - name: Run test
        run: pytest Lab_7/env_416404/calculator_test.py::test_srednia

